
@contentType = application/json
@apiUrl = http://localhost:3000/customer

###
# @name createCustomer
POST {{apiUrl}}
content-type: {{contentType}}

{
    "firstName": "name {{$randomInt 1 500}}",
    "surName": "surname {{$randomInt 1 500}} ",
    "email": "{{$randomInt 1 500}}@gmail.com",
    "password": "prm260110",
    "document": "31111111111",
    "documentType": "CPF",
    "balance": 100
}

###
# @name getCustomerById
@customerId =  50ed3071-7ad1-4d6b-8028-d343dd308b48
GET  {{apiUrl}}/{{customerId}}


###
# @name getBalance
@customerId =  50ed3071-7ad1-4d6b-8028-d343dd308b48
GET  {{apiUrl}}/balance/{{customerId}}