
@contentType = application/json
@apiUrl = http://localhost:3000/customer

###
# @name createCustomer
POST {{apiUrl}}
content-type: {{contentType}}

{
    "firstName": "name {{$randomInt 1 500}}",
    "surName": "surname {{$randomInt 1 500}} ",
    "email": "{{$randomInt 1 500}}@gmail.com",
    "password": "prm260110",
    "document": "31111111111",
    "documentType": "CPF",
    "balance": 100
}
###
@customerId =  {{createCustomer.response.body.customer_id}}


###
# @name getCustomerById
GET  {{apiUrl}}/{{customerId}}


###
# @name getBalance
GET  {{apiUrl}}/balance/{{customerId}}

###
# @name ListCustomer
@page = 1
@per_page = 10
@sort = firstName
@sort_dir = desc
@filter = name
GET  {{apiUrl}}?page={{page}}&per_page={{per_page}}&sort={{sort}}&sort_dir={{sort_dir}}&filter={{filter}}

