version: '3.9'
services:
  app:
    container_name: picpay-api
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./src:/home/node/app/src
      - ./libs:/home/node/app/libs
    env_file:
      - .env
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
    expose:
      - ${HTTP_PORT}
    depends_on:
      - mysql
    command: npm run start:dev

  mysql:
    image: mysql:8
    container_name: picpay-db
    volumes:
      - db:/var/lib/mysql
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_HOST=${DB_HOST}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    expose:
      - ${DB_PORT}

  rabbit:
    image: 'rabbitmq:3-management'
    hostname: my-rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: 'SWQOKODSQALRPCLNMEQG'
      RABBITMQ_DEFAULT_PASS: 'admin'
      RABBITMQ_DEFAULT_USER: 'admin'

    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672

volumes:
  db:
