version: '3.9'
services:
  app:
    container_name: app-transaction
    build:
      context: .
      dockerfile: Dockerfile   
    volumes:
      - .:/home/node/app 
    ports:
      - 3000:3000
    expose:
      - 3000
    depends_on:
      - mysql
    command: ./.docker/start.sh

  mysql:
    image: mysql:8.0.30-debian
    volumes:
      - db:/var/lib/mysql
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=transaction
      - MYSQL_ROOT_PASSWORD=root
    tmpfs: 
      - /var/lib/mysql
    # remove logs desnecessários  
    security_opt:
      - seccomp:unconfined
    ports:
      - 3306:3306
    expose:
      - 3306

  # rabbit:
  #   image: 'rabbitmq:3-management'
  #   hostname: my-rabbitmq
  #   environment:
  #     RABBITMQ_ERLANG_COOKIE: 'SWQOKODSQALRPCLNMEQG'
  #     RABBITMQ_DEFAULT_PASS: 'admin'
  #     RABBITMQ_DEFAULT_USER: 'admin'

  #   volumes:
  #     - ./rabbitmq-data:/var/lib/rabbitmq
  #   ports:
  #     - 15672:15672
  #     - 5672:5672

volumes:
  db:
