name: 'Continuos Integration'

on: [push, pull_request]

jobs:
  install:
    name: 'Installing depedencies'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{runner.os}}-${{hashFiles('**/package-lock.json')}}

      - name: Install depedencies
        run: npm install

  testing:
    name: 'Run Unit Test'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Restore node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{runner.os}}-${{hashFiles('**/package-lock.json')}}

      - name: Run unit test
        run: npm run test
